### PR TITLE
Updating Bahasa Indonesia

### PR DESCRIPTION
**Pull request by pc-v2**
Sorry for re-doing pull requests
I accidentally revert this resx

`cbSettingsBatteryDarkMode`

> Nyalakan mode gelap bila perangkat terputus dari saklar daya

`cbSettingsEnergySaverMitigation`

> Pencegahan penghematan daya untuk berganti tema

`cbSettingsEnergySaverMitigationInfo
`
> Opsi ini hanya berfungsi jika anda tidak menyalakan penghematan daya secara manual

### CODE REVIEW

**Comment by Armin2208** [comment]
can I merge only the first commit (Updating Bahasa Indonesia)?

**Comment by pc-v2** [comment]
> 
> 
> can I merge only the first commit (Updating Bahasa Indonesia)?

yes!!!

**Comment by pc-v2** [comment]
sorry, i think i need to learn more about git

**Comment by Armin2208** [comment]
me too! I don't know if and how I can merge only one commit :D

**Pull request closed without merging**
