### PR TITLE
Update Traditional Chinese translation

### PR DESCRIPTION
**Pull request by SiderealArt**

### CODE REVIEW

**Comment by Spiritreader** [comment]
Hello!

We have recently added translation improvements from December last year.
https://github.com/Armin2208/Windows-Auto-Night-Mode/pull/187/commits/11122598f94f606e2acba6982be466580564d407

Are your changes still relevant?

**Comment by SiderealArt** [comment]
Yes, This pull request includes all the strings from Auto Night Mode X

**Comment by Spiritreader** [comment]
Alright, thank you. We have some conflicts in the PR. 
Could you resolve them first so we can merge?

**Comment by SiderealArt** [comment]
I'll just close this PR and open a new one.

**Pull request closed without merging**
