### PR TITLE
Replace SunDate.cs with SunriseCalculator

### PR DESCRIPTION
**Pull request by jwfxpr**
As per #236 and microsoft/PowerToys#1331, replacing `SunDate.cs` with [jwfxpr/SunriseCalculator](https://github.com/jwfxpr/SunriseCalculator) to allow for license flexibility. Should also result in more reliable sunrise/set results.

Tested this locally using my own real location, seems to be working as expected within a minute or two each way.

Auto-Night-Mode with new library:
image

Windows Night light:
image

Google:
image

In this PR, SunriseCalculator has been added to the repository as a [`git submodule`](https://git-scm.com/book/en/v2/Git-Tools-Submodules), so that improvements or corrections to the library can be easily `pull`ed into your project later if you desire. I also moved the unit testing code into a nested submodule and set `fetchRecurseSubmodules = false` so that the MSTest dependency of the unit tests doesn't interfere with your existing project dependencies.

Take a quick look, test out the fork for yourself, and let me know if it's okay.

### CODE REVIEW

**Comment by Spiritreader** [comment]
Looks all good from my end!
Nice work, thank you very much!

**Comment by jwfxpr** [comment]
Re 2fdfa5d, deleting `SunDate.cs` also removed the requirement (and validity) of `using AutoDarkModeApp;` throughout `AutoDarkModeSvc`, so in order to compile (to test a theory) I removed them too.

And thanks for the compliment! 😊

**Comment by jwfxpr** [comment]
Just noticed this is still open at 14 days, anything I can do/fix to help with it?

**Comment by Spiritreader** [comment]
I have already informed @Armin2208 to merge the PR. I am going to get this in motion.

**Comment by Armin2208** [comment]
great code

**Comment by Armin2208** [comment]
thanks and much love

**Comment by jwfxpr** [comment]
Cheers, glad to help!

**Comment by Armin2208** [comment]
sorry I was and I am a little bit busy, but Auto Dark Mode 10 should be ready for Windows 11 launch

**Pull request merged**
